spring.application.name=fitple

# MySQL jung-bo
spring.datasource.url=jdbc:mysql://localhost:3306/fitple?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=sim08161210
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA jung-bo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server jung-bo
server.port=8080

openai.api.key=${OPENAI_API_KEY}